import type { PlaneDef, PlaneId } from "./types";

export const PLANES: PlaneDef[] = [
  {
    id: "camel",
    name: "Sopwith Camel",
    short: "CAMEL",
    nation: "RFC",
    year: "1917",
    role: "Caza biplano",
    blurb: "Nervioso, letal a corta distancia. El as de la Gran Guerra.",
    speed: 52,
    turn: 1,
    climb: 0.72,
    firepower: 0.7,
    armor: 0.55,
    ammo: 48,
    layout: "biplane",
    unlock: { type: "start" },
    colors: {
      fuse: 0x6b5a3a,
      wing: 0x5c6b48,
      accent: 0xc9c2b0,
      cowl: 0x3a342c,
      strut: 0x2a241c,
    },
  },
  {
    id: "fokker",
    name: "Fokker Dr.I",
    short: "DR.I",
    nation: "Luftstreitkräfte",
    year: "1917",
    role: "Triplano",
    blurb: "El circo rojo. Gira como un halcón, trepa como un fantasma.",
    speed: 48,
    turn: 1.18,
    climb: 0.8,
    firepower: 0.75,
    armor: 0.5,
    ammo: 44,
    layout: "triplane",
    unlock: { type: "kills", n: 8 },
    colors: {
      fuse: 0x8a1e1a,
      wing: 0x7a1814,
      accent: 0xc9b48a,
      cowl: 0x2a2420,
      strut: 0x1a1612,
    },
  },
  {
    id: "spad",
    name: "SPAD S.XIII",
    short: "SPAD",
    nation: "Aéronautique",
    year: "1917",
    role: "Caza de picado",
    blurb: "Rápido en línea recta. Picado limpio, ráfaga corta.",
    speed: 58,
    turn: 0.86,
    climb: 0.7,
    firepower: 0.85,
    armor: 0.65,
    ammo: 52,
    layout: "biplane",
    unlock: { type: "mission", n: 2 },
    colors: {
      fuse: 0x6a5a3c,
      wing: 0x4a5a3a,
      accent: 0xb03030,
      cowl: 0x3a3830,
      strut: 0x2c281e,
    },
  },
  {
    id: "albatros",
    name: "Albatros D.Va",
    short: "D.VA",
    nation: "Luftstreitkräfte",
    year: "1917",
    role: "Sesquiplano",
    blurb: "Fuselaje de tiburón y ala inferior corta. Elegante y cruel.",
    speed: 54,
    turn: 0.92,
    climb: 0.68,
    firepower: 0.8,
    armor: 0.6,
    ammo: 50,
    layout: "sesqui",
    unlock: { type: "kills", n: 16 },
    colors: {
      fuse: 0xb8a05a,
      wing: 0x3d5a48,
      accent: 0x7a1c18,
      cowl: 0x2e2a24,
      strut: 0x241e16,
    },
  },
  {
    id: "spitfire",
    name: "Spitfire Mk.I",
    short: "SPIT",
    nation: "RAF",
    year: "1939",
    role: "Caza elíptico",
    blurb: "Ala elíptica, motor cantando. El cielo de Inglaterra.",
    speed: 78,
    turn: 1.05,
    climb: 0.9,
    firepower: 0.95,
    armor: 0.7,
    ammo: 64,
    layout: "mono",
    unlock: { type: "mission", n: 4 },
    colors: {
      fuse: 0x4a5840,
      wing: 0x3e4a38,
      accent: 0xc9c4b8,
      cowl: 0x3a4034,
      strut: 0x2a2e28,
    },
  },
  {
    id: "mustang",
    name: "P-51 Mustang",
    short: "P-51",
    nation: "USAAF",
    year: "1942",
    role: "Escolta largo",
    blurb: "Alcance transoceánico. El cazador de escoltas.",
    speed: 86,
    turn: 0.9,
    climb: 0.88,
    firepower: 1.05,
    armor: 0.8,
    ammo: 72,
    layout: "mono",
    unlock: { type: "mission", n: 5 },
    colors: {
      fuse: 0x6a6848,
      wing: 0x5c5a40,
      accent: 0xc9c8c0,
      cowl: 0x3a382c,
      strut: 0x2a281e,
    },
  },
  {
    id: "bf109",
    name: "Bf 109 E",
    short: "109",
    nation: "Luftwaffe",
    year: "1939",
    role: "Caza angular",
    blurb: "Nariz amarilla, trepada brutal. El enemigo de la Batalla.",
    speed: 82,
    turn: 0.88,
    climb: 0.96,
    firepower: 1,
    armor: 0.72,
    ammo: 60,
    layout: "mono",
    unlock: { type: "kills", n: 28 },
    colors: {
      fuse: 0x5a6454,
      wing: 0x4a5446,
      accent: 0xc9a03a,
      cowl: 0xc9a03a,
      strut: 0x2a2e28,
    },
  },
  {
    id: "zero",
    name: "A6M Zero",
    short: "ZERO",
    nation: "Kaigun",
    year: "1940",
    role: "Caza naval",
    blurb: "Ligero como papel, gira donde otros se rompen.",
    speed: 74,
    turn: 1.22,
    climb: 0.84,
    firepower: 0.9,
    armor: 0.48,
    ammo: 56,
    layout: "mono",
    unlock: { type: "mission", n: 6 },
    colors: {
      fuse: 0x6a7460,
      wing: 0x5e6856,
      accent: 0x9a2b2b,
      cowl: 0x2e2c28,
      strut: 0x24221e,
    },
  },
];

export const PLANE_MAP: Record<PlaneId, PlaneDef> = Object.fromEntries(
  PLANES.map((p) => [p.id, p]),
) as Record<PlaneId, PlaneDef>;

export function planeById(id: PlaneId): PlaneDef {
  return PLANE_MAP[id];
}

export function isUnlocked(id: PlaneId, kills: number, completed: number[]): boolean {
  const u = planeById(id).unlock;
  if (u.type === "start") return true;
  if (u.type === "kills") return kills >= u.n;
  return completed.includes(u.n);
}

export function unlockHint(id: PlaneId): string {
  const u = planeById(id).unlock;
  if (u.type === "start") return "Disponible";
  if (u.type === "kills") return `${u.n} derribos`;
  return `Misión ${u.n}`;
}
